### ISSUE TITLE
TensorRT-LLM RuntimeError: shape '[3, 4096, 4096]' is invalid for input of size 25165824

### ISSUE THREAD

**Issue by qinzhenyi1314** [THUDM/CogVLM2#101]
### System Info / 系統信息

cuda_12.4.r12.4/compiler.34097967_0
Python 3.10.12
tensorrt                 10.0.1
tensorrt-cu12            10.0.1
tensorrt-cu12-bindings   10.0.1
tensorrt-cu12-libs       10.0.1
tensorrt-llm             0.11.0.dev2024061100
torch                    2.3.0
torchvision              0.18.1
transformers             4.40.2

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

`root@fed30c1a0ccc:/data/workspace/github/TensorRT-LLM/examples/cogvlm# python3 convert_checkpoint.py --model_dir /data/workspace/huggingFace/models--THUDM--cogvlm2-llama3-chat-19B/snapshots/2bf7de6892877eb50142395af14847519ba95998/ --output_dir ./cogvlm2-llama3-chat-19B
[TensorRT-LLM] TensorRT-LLM version: 0.11.0.dev2024061100
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.39it/s]
[06/14/2024-10:34:58] Some parameters are on the meta device device because they were offloaded to the cpu.
Traceback (most recent call last):
  File "/data/workspace/github/TensorRT-LLM/examples/cogvlm/convert_checkpoint.py", line 519, in <module>
    main()
  File "/data/workspace/github/TensorRT-LLM/examples/cogvlm/convert_checkpoint.py", line 496, in main
    covert_and_save(rank)
  File "/data/workspace/github/TensorRT-LLM/examples/cogvlm/convert_checkpoint.py", line 470, in covert_and_save
    weights = convert_hf_cogvlm(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/cogvlm/convert.py", line 55, in convert_hf_cogvlm
    split_v = split_qkv_tp(qkv_weight, num_attention_heads, hidden_size,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 409, in split_qkv_tp
    v = v.reshape(3, n_hidden, n_hidden)
RuntimeError: shape '[3, 4096, 4096]' is invalid for input of size 25165824
`

### Expected behavior / 期待表现

希望帮助确认报错原因

**Comment by leizhao1234** [comment]
trtllm只支持cogvlm1
