### ISSUE TITLE
Cuda Out Of Memory

### ISSUE THREAD

**Issue by Grimmins** [THUDM/CogVLM2#102]
### System Info / 系統信息

Cuda 12.5
Trasnformers 4.41.2
Python 3.12
Ubuntu 22.04
NVIDIA RTX 4090 - 24Gb RAM

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

I tried the code example on HuggingFace and just ran it
and here the traceback : 

Traceback (most recent call last):
  File "/home/nabab/PycharmProjects/pythonProject/cogvlm2.py", line 18, in <module>
    ).to(DEVICE).eval()
      ^^^^^^^^^^
  File "/home/nabab/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2724, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nabab/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/nabab/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/home/nabab/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/home/nabab/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/home/nabab/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/nabab/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
           ^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU

### Expected behavior / 期待表现

Chat between Ai assistant and user

**Comment by zRzRzRzRzRzRzR** [comment]
这个模型需要42G显存 建议使用int4 模型

**Comment by Grimmins** [comment]
how do you run it in int4 with the code given in HF? I've tried all the dtypes suggested by torch and none of them work.

**Comment by Grimmins** [comment]
@zRzRzRzRzRzRzR hey, the question is how to launch it in int4 with the code provided on HF? thank you !
