### ISSUE TITLE
CogVLM2 Videos demo

### ISSUE THREAD

**Issue by josephzpng** [THUDM/CogVLM2#144]
### System Info / 系統信息

cuda11.7
torch2.0.0

### Who can help? / 谁可以帮助到您？

run python cli_video_demo.py
---》〉》
RuntimeError: Input type (float) and bias type (c10::Half) should be the same

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

run python cli_video_demo.py

### Expected behavior / 期待表现

no

**Comment by huangshiyu13** [comment]
fix in this issue: https://github.com/THUDM/CogVLM2/issues/137

**Comment by josephzpng** [comment]
Thank you for your reply. The old problem has been solved, but a new problem has arisen.

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Floating point exception (core dumped)

Looking forward to your reply!
env: torch2.0.0+cu117

**Comment by Cherryjingyao** [comment]
I also meet an error 
`huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Traceback (most recent call last):
  File "test_demo/test_cogvlm2_video.py", line 136, in <module>
    outputs = model.generate(**inputs, **gen_kwargs)
  File "/data/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/transformers/generation/utils.py", line 1914, in generate
    result = self._sample(
  File "/data/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/transformers/generation/utils.py", line 2651, in _sample
    outputs = self(
  File "/data/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/pfs-data/huggingface/modules/transformers_modules/THUDM/cogvlm2-video-llama3-chat/ca14f13b05f5ead425188aae3e5e725bf4905cd1/modeling_cogvlm.py", line 635, in forward
    outputs = self.model(
  File "/data/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/pfs-data/huggingface/modules/transformers_modules/THUDM/cogvlm2-video-llama3-chat/ca14f13b05f5ead425188aae3e5e725bf4905cd1/modeling_cogvlm.py", line 416, in forward
    return self.llm_forward(
  File "/pfs-data/huggingface/modules/transformers_modules/THUDM/cogvlm2-video-llama3-chat/ca14f13b05f5ead425188aae3e5e725bf4905cd1/modeling_cogvlm.py", line 465, in llm_forward
    past_key_values_length = past_key_values[0][0].shape[2]
AttributeError: 'str' object has no attribute 'shape'
`

**Comment by huangshiyu13** [comment]
try this: `pip install transformer==4.40`

**Comment by josephzpng** [comment]
> try this: `pip install transformers==4.40`

I tried using transformers 4.40.0;
Whether I use quant8 or quant4, the following problem is thrown:

>>----------
Run CUDA_VISIBLE_DEVICES=2 python cli_video_demo.py --quant 8
------------------------------
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Floating point exception (core dumped)
>>----------

Looking forward to your reply!
env: torch2.0.0+cu117, transformers4.40.0, bitsandbytes0.42.0(I can't install 0.43.1 here)
device: V100

**Comment by supersteve2001** [comment]
> > try this: `pip install transformers==4.40`
> 
> I tried using transformers 4.40.0; Whether I use quant8 or quant4, the following problem is thrown:
> 
> > >
> 
> ## Run CUDA_VISIBLE_DEVICES=2 python cli_video_demo.py --quant 8
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks... To disable this warning, you can either: - Avoid using `tokenizers` before the fork if possible - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false) Floating point exception (core dumped)
> 
> > >
> 
> Looking forward to your reply! env: torch2.0.0+cu117, transformers4.40.0, bitsandbytes0.42.0(I can't install 0.43.1 here) device: V100

I found the similar question, while run cli_demo_multi_gpus.py; after input image and question; get single feedback:
Floating point exception (core dumped)
I'm also currently use  v100.

**Comment by supersteve2001** [comment]
torch2.0.0+cu117, transformers4.40.0, bitsandbytes 0.43.1

**Comment by supersteve2001** [comment]
I found v100 couldn't support bf16, and demo uses fp16. I wish it can help

**Comment by josephzpng** [comment]
> Thank you for your reply. 
I found that fp16 seems to have some problems. I tried it on A100 and used bf16 and it can perform inference smoothly.

**Comment by josephzpng** [comment]
> I found v100 couldn't support bf16, and demo uses fp16. I wish it can help

Thank you for your reply!
I found that fp16 seems to have some problems. I tried it on A100 and used bf16 and it can perform inference smoothly.

**Comment by davidsouza-protex** [comment]
> transformers==4.40

This version of Transformers worked here.
