### ISSUE TITLE
web_demo THUDM/cogvlm2-llama3-chinese-chat-19B 

### ISSUE THREAD

**Issue by gehong-coder** [THUDM/CogVLM2#23]
### System Info / 系統信息

python:3.11
xformers :0.0.26.post1
transformers: 4.41.0

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### 代码
MODEL_PATH = "THUDM/cogvlm2-llama3-chinese-chat-19B"
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
TORCH_TYPE = torch.bfloat16 if torch.cuda.is_available() and torch.cuda.get_device_capability()[
    0] >= 8 else torch.float16
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(MODEL_PATH, torch_dtype=TORCH_TYPE, trust_remote_code=True, load_in_4bit=True,low_cpu_mem_usage=True).eval()

### 错误
Traceback (most recent call last):
  File "/data/users/hongge/miniconda3/envs/cog/bin/chainlit", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/data/users/hongge/miniconda3/envs/cog/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/hongge/miniconda3/envs/cog/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/data/users/hongge/miniconda3/envs/cog/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/hongge/miniconda3/envs/cog/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/hongge/miniconda3/envs/cog/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/hongge/miniconda3/envs/cog/lib/python3.11/site-packages/chainlit/cli/__init__.py", line 154, in chainlit_run
    run_chainlit(target)
  File "/data/users/hongge/miniconda3/envs/cog/lib/python3.11/site-packages/chainlit/cli/__init__.py", line 56, in run_chainlit
    load_module(config.run.module_name)
  File "/data/users/hongge/miniconda3/envs/cog/lib/python3.11/site-packages/chainlit/config.py", line 409, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/nfs/dev-uclai-alginfra-5/data/users/hongge/workspace/github/CogVLM2/basic_demo/web_demo.py", line 19, in <module>
    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/users/hongge/miniconda3/envs/cog/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 909, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.THUDM.cogvlm2-llama3-chinese-chat-19B.c95db649866bb0c0fcc383e95e87e1b01d7d956a.configuration_cogvlm.CogVLMConfig'> to build an AutoTokenizer.

### Expected behavior / 期待表现

CogVLM2/basic_demo/web_demo.py
中文模型为啥不能用呢

**Comment by todaydeath** [comment]
这个问题解决了么

**Comment by todaydeath** [comment]
@gehong-coder 请问这个问题怎么解决啊，我用的模型是cogvlm2-llama3-chinese-chat-19B，报错信息：
Traceback (most recent call last):
  File "/mnt/sdd/hwb/large_model/tsinghua/cogvlm2/code/basic_demo/web_demo.py", line 19, in <module>
    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)
  File "/root/anaconda3/envs/cogvlm2/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 909, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.configuration_cogvlm.CogVLMConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, AlignConfig, BarkConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, BrosConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, ClvpConfig, LlamaConfig, CodeGenConfig, CohereConfig, ConvBertConfig, CpmAntConfig, CTRLConfig, Data2VecAudioConfig, Data2VecTextConfig, DbrxConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig, FalconConfig, FastSpeech2ConformerConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GemmaConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GroundingDinoConfig, GroupViTConfig, HubertConfig, IBertConfig, IdeficsConfig, Idefics2Config, InstructBlipConfig, JambaConfig, JetMoeConfig, JukeboxConfig, Kosmos2Config, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LlamaConfig, LlavaConfig, LlavaNextConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MambaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MgpstrConfig, MistralConfig, MixtralConfig, MobileBertConfig, MPNetConfig, MptConfig, MraConfig, MT5Config, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, NezhaConfig, NllbMoeConfig, NystromformerConfig, OlmoConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, Owlv2Config, OwlViTConfig, PaliGemmaConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, PersimmonConfig, PhiConfig, Phi3Config, Pix2StructConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RagConfig, RealmConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, SeamlessM4TConfig, SeamlessM4Tv2Config, SiglipConfig, Speech2TextConfig, Speech2Text2Config, SpeechT5Config, SplinterConfig, SqueezeBertConfig, StableLmConfig, Starcoder2Config, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, TvpConfig, UdopConfig, UMT5Config, VideoLlavaConfig, ViltConfig, VipLlavaConfig, VisualBertConfig, VitsConfig, Wav2Vec2Config, Wav2Vec2BertConfig, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig
