### ISSUE TITLE
使用openai_api_demo的时候，如果初始没有图片，会报错：IndexError: list index out of range

### ISSUE THREAD

**Issue by jiaolongxue** [THUDM/CogVLM2#51]
### System Info / 系統信息

cuda和pytorch版本 ：pytorch/pytorch:2.1.2-cuda12.1-cudnn8-devel

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

日志

```
INFO:     192.168.18.83:56502 - "POST /v1/chat/completions HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/opt/conda/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/xiaoshi-vl-chat/openai_api_demo.py", line 164, in create_chat_completion
    response = generate_cogvlm(model, tokenizer, gen_params)
  File "/opt/xiaoshi-vl-chat/openai_api_demo.py", line 216, in generate_cogvlm
    for response in generate_stream_cogvlm(model, tokenizer, params):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/opt/xiaoshi-vl-chat/openai_api_demo.py", line 285, in generate_stream_cogvlm
    input_by_model = model.build_conversation_input_ids(tokenizer, query=query, history=history, images=[image_list[-1]])
IndexError: list index out of range
```

### Expected behavior / 期待表现

作为 OpenAI-API-compatible添加到dify的时候，初始会有一个校验，这个时候没有图片数据，希望能够兼容这种情况

**Comment by zRzRzRzRzRzRzR** [comment]
目前的逻辑是一定要有图片的，直接对话效果很差

**Comment by Summer-nan** [comment]
想问一下，使用openai_api_demo后，如何使用ip访问呀

**Comment by xzm123456** [comment]
+1，想问下楼主的参数设置，我直接访问IP是有问题的。。。。，怎么搞都不对。
感谢楼主的回答，谢谢。

**Comment by zRzRzRzRzRzRzR** [comment]
一定是要传入图片的，cogvlm的第一个对话一定要带有图片
