### ISSUE TITLE
4张12G的显卡仍然 torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by fishfree** [THUDM/CogVLM2#64]
### System Info / 系統信息

![image](https://github.com/THUDM/CogVLM2/assets/1741341/f88f0936-6ce5-47b6-8dcf-ad677cf034de)

conda Python 3.11

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

先把`cli_demo_multi_gpus.py`文件里的模型改成了`cogvlm2-llama3-chinese-chat-19B`，然后执行`python cli_demo_multi_gpus.py`，结果如下：
```
***省略了****
Loading checkpoint shards: 100%|█████████████████████| 8/8 [00:01<00:00,  7.85it/s]
Traceback (most recent call last):                                                 
  File "/mnt/data/mememe/CogVLM2/basic_demo/cli_demo_multi_gpus.py", line 51, in <module>
    model = load_checkpoint_and_dispatch(model, MODEL_PATH, device_map=device_map, dtype=TORCH_TYPE)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/mememe/miniconda3/envs/cogvlm2/lib/python3.11/site-packages/accelerate/big_modeling.py", line 607, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "/mnt/data/mememe/miniconda3/envs/cogvlm2/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 1736, in load_checkpoint_in_model
    set_module_tensor_to_device(
  File "/mnt/data/mememe/miniconda3/envs/cogvlm2/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 366, in set_module_tensor_to_device
    value = value.to(dtype)
            ^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU
``` 

根据[代码](https://github.com/THUDM/CogVLM2/blob/2d58b1d144988dc0270de39b7af3476adb840c6c/basic_demo/cli_demo_multi_gpus.py#L43)里计算，应该每张卡的是42/4=10点多。怎么还是out of memory呢？

### Expected behavior / 期待表现

应该跑得起来才对。

**Comment by tiandazhao** [comment]
我五张40G显卡也会OOM

**Comment by zRzRzRzRzRzRzR** [comment]
最多在3张每张16G的显卡上加载，有部分模块不能拆分
