### ISSUE TITLE
Unsuccessful execution for basic_demo/cli_demo.py

### ISSUE THREAD

**Issue by bucket-xv** [THUDM/CogVLM2#73]
### System Info / 系統信息

Cuda 11.8
transformers 4.41.1 
Python 3.12.3
Ubuntu 20.04.6 LTS
**triton 2.2.0**

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

```bash
# conda create and activate
cd Path/To/basic_demo
```

```bash
# I have to install torch first or xformer will report error
pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118

pip install -r requirements.txt

# I have to install triton to run cli_demo.py
pip install triton
```

And this is my execution command:
```bash
CUDA_VISIBLE_DEVICES=0 python cli_demo.py --quant 8
```

Here is the error info
```bash
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/xuchenhao/realnav/CogVLM2/basic_demo/cli_demo.py", line 45, in <module>
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xuchenhao/.conda/envs/cogvlm2/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 550, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xuchenhao/.conda/envs/cogvlm2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 510, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xuchenhao/.conda/envs/cogvlm2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 208, in get_class_in_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/xuchenhao/huggingface/modules/transformers_modules/THUDM/cogvlm2-llama3-chat-19B/2bf7de6892877eb50142395af14847519ba95998/modeling_cogvlm.py", line 20, in <module>
    from .visual import EVA2CLIPModel
  File "/home/xuchenhao/huggingface/modules/transformers_modules/THUDM/cogvlm2-llama3-chat-19B/2bf7de6892877eb50142395af14847519ba95998/visual.py", line 4, in <module>
    import xformers.ops as xops
  File "/home/xuchenhao/.conda/envs/cogvlm2/lib/python3.12/site-packages/xformers/ops/__init__.py", line 8, in <module>
    from .fmha import (
  File "/home/xuchenhao/.conda/envs/cogvlm2/lib/python3.12/site-packages/xformers/ops/fmha/__init__.py", line 10, in <module>
    from . import (
  File "/home/xuchenhao/.conda/envs/cogvlm2/lib/python3.12/site-packages/xformers/ops/fmha/triton_splitk.py", line 548, in <module>
    _get_splitk_kernel(num_groups)
  File "/home/xuchenhao/.conda/envs/cogvlm2/lib/python3.12/site-packages/xformers/ops/fmha/triton_splitk.py", line 503, in _get_splitk_kernel
    _fwd_kernel_splitK_unrolled = unroll_varargs(_fwd_kernel_splitK, N=num_groups)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xuchenhao/.conda/envs/cogvlm2/lib/python3.12/site-packages/xformers/triton/vararg_kernel.py", line 166, in unroll_varargs
    jitted_fn = triton.jit(fn)
                ^^^^^^^^^^^^^^
  File "/home/xuchenhao/.conda/envs/cogvlm2/lib/python3.12/site-packages/triton/runtime/jit.py", line 707, in jit
    return decorator(fn)
           ^^^^^^^^^^^^^
  File "/home/xuchenhao/.conda/envs/cogvlm2/lib/python3.12/site-packages/triton/runtime/jit.py", line 698, in decorator
    return JITFunction(
           ^^^^^^^^^^^^
  File "/home/xuchenhao/.conda/envs/cogvlm2/lib/python3.12/site-packages/triton/runtime/jit.py", line 577, in __init__
    self.starting_line_number = inspect.getsourcelines(fn)[1]
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xuchenhao/.conda/envs/cogvlm2/lib/python3.12/inspect.py", line 1270, in getsourcelines
    return getblock(lines[lnum:]), lnum + 1
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xuchenhao/.conda/envs/cogvlm2/lib/python3.12/inspect.py", line 1237, in getblock
    for _token in tokens:
  File "/home/xuchenhao/.conda/envs/cogvlm2/lib/python3.12/tokenize.py", line 582, in _generate_tokens_from_c_tokenizer
    raise TokenError(msg, (e.lineno, e.offset)) from None
tokenize.TokenError: ('unterminated string literal (detected at line 1122)', (1122, 1))
```

### Expected behavior / 期待表现

Run the demo successfully

**Comment by bucket-xv** [comment]
Well, it seems that `python=3.11` and `triton=2.1.0` may help. After all, `triton>=2.2.0` seems to force `cuda >= 12.0`, but in my case `cuda=11.8`.

I suggest add more specification of `triton` in `requirements.txt`?

**Comment by Grimmins** [comment]
same error, and i've python 3.12, triton 2.3
yep adding triton in requirements => good
an idea to solve ?

**Comment by zRzRzRzRzRzRzR** [comment]
if you install xformers and use Linux it will install triton automatically

**Comment by pechpo** [comment]
Degrading xformers to 0.0.24 has solved my problem.
